---
title: "Task 19"
author: "Sabrina Olmo"
date: "11/8/2022"
output:
  html_document:
    keep_md: yes
    code_folding: hide
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, message = FALSE}
library(tidyverse)
library(USAboundaries)
library(sf)
library(maps)
library(ggrepel)
library(ggsflabel)
library(leaflet)
```

```{r Gathering Data}
USmap <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
ID <- us_counties(states = "ID")
cities <- us_cities()
top3 <- cities %>%
          filter(state_name != "Alaska", state_name != "Hawaii") %>%
          mutate(full_name = str_c(city,",", " ", state_abbr)) %>%
          group_by(state_name) %>%
          arrange(desc(population)) %>%
          slice(1:3)

first <- top3 %>%
          slice(1:1)

second <- top3 %>%
            slice(2:2)

third <- top3 %>%
            slice(3:3)
```

```{r Plot}
leaflet(data = top3) %>%
  addTiles() %>%
  addMarkers(popup = ~as.character(population), 
             label = ~full_name)
```