---
title: "Tues Aug 30"
author: "Sabrina Olmo"
date: "8/31/2022"
output:
  html_document:
    theme: cosmo
    keep_md:  true 
editor_options: 
  chunk_output_type: console
---

```{r}
library(knitr)
```

```{r}
sin(pi/4)
x <- 10/3
``` 

#Names allowed: Sabrina, Seth
#Names not allowed: Ruth, Ross because they start with the letter R

(MySequence <- seq(1, 50, length.out = 7))

```{r}
my_vector <- c(1, 5, 12, 31, 19)
my_vector
```

7+5==12
#= is used for assignments while == is used to test for equality

(7+4==12)|(5-4==1)
#I got a True output because at least one of the clauses I inputed is actually true.

```{r Ch. 4 Excercsie 1}
#1
my_variable <- 10
my_varıable
#This code does not work because there a small typo in the word variable where the 'i' is not inputted correctly
```

```{r Ch. 4 Excersise 2}
library(tidyverse)

#ggplot(dota = mpg) + 
  #geom_point(mapping = aes(x = displ, y = hwy))

#fliter(mpg, cyl = 8)
#filter(diamond, carat > 3)

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

filter(mpg, cyl = 8)
filter(diamond, carat > 3)
```

```{r Ch. 4 Excersise 3}
#The command knits the document and we can do this by clicking knit on the top menu of the terminal.
```

